services:
  pgvector-${IMG_POSTFIX}:
    image: ${PGVECTOR_IMAGE}
    container_name: ${PGVECTOR_HOST}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGVECTOR_USER}
      POSTGRES_PASSWORD: ${PGVECTOR_PASSWORD}
      POSTGRES_DB: ${PGVECTOR_DB}
    ports:
      - ${PGVECTOR_PORT}:5432
    volumes:
      - pgvector-${IMG_POSTFIX}-data:/var/lib/postgresql/data:rw
    networks:
      ${IMG_POSTFIX}_net_int:
        ipv4_address: ${PGVECTOR_INTERNAL}

  postgres-${IMG_POSTFIX}:
    image: ${POSTGRESDB_IMAGE}
    container_name: ${POSTGRESDB_HOST}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_DB}
    ports:
      - ${POSTGRESDB_PORT}:5432
    volumes:
      - postgres-${IMG_POSTFIX}-data:/var/lib/postgresql/data:rw
    networks:
      ${IMG_POSTFIX}_net_int:
        ipv4_address: ${POSTGRESDB_INTERNAL}

  redis-${IMG_POSTFIX}:
    image: ${REDIS_IMAGE}
    container_name: ${REDIS_HOST}
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-${IMG_POSTFIX}-data:/data
    restart: always
    networks:
      ${IMG_POSTFIX}_net_int:
        ipv4_address: ${REDIS_INTERNAL}

  mongodb-${IMG_POSTFIX}:
    image: ${MONGODB_IMAGE}
    container_name: ${MONGODB_HOST}
    restart: always
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongodb-${IMG_POSTFIX}-data:/data/db
    networks:
      ${IMG_POSTFIX}_net_int:
        ipv4_address: ${MONGODB_INTERNAL}

  langflow-${IMG_POSTFIX}:
    image: ${LANGFLOW_IMAGE}
    container_name: ${LANGFLOW_HOST}
    restart: unless-stopped
    depends_on:
      - pgvector-${IMG_POSTFIX}
      - postgres-${IMG_POSTFIX}
      - redis-${IMG_POSTFIX}
    ports:
      - ${LANGFLOW_PORT}:7860
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_DB}
    volumes:
      - ./langflow/src/tis_components/:/app/tis_components
      - ./langflow/logs:/app/logs
      - ./langflow/data:/app/data
    networks:
      ${IMG_POSTFIX}_net_int:
        ipv4_address: ${LANGFLOW_INTERNAL}

networks:
  ${IMG_POSTFIX}_net_int:
    driver: bridge
    ipam:
      config:
        - subnet: ${INTERNAL_SUBNET}

volumes:
  pgvector-${IMG_POSTFIX}-data:
    name: pgvector-${IMG_POSTFIX}-data
    driver: local
  postgres-${IMG_POSTFIX}-data:
    name: postgres-${IMG_POSTFIX}-data
    driver: local
  redis-${IMG_POSTFIX}-data:
    name: redis-${IMG_POSTFIX}-data
    driver: local
  mongodb-${IMG_POSTFIX}-data:
    name: mongodb-${IMG_POSTFIX}-data
    driver: local
