services:
  pgvector-fe:
    image: fetest-pgvector-fe
    container_name: pgvector-fe
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fetest-db
    ports:
      - 5432:5432
    volumes:
      - pgvector-fe-data:/var/lib/postgresql/data:rw
    networks:
      fe_net_int:
        ipv4_address: 10.0.111.100

  postgres-fe:
    image: fetest-postgres-fe
    container_name: postgres-fe
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: langflow
    ports:
      - 5433:5432
#    volumes:
#      - postgres-fe-data:/var/lib/postgresql/data:rw
    networks:
      fe_net_int:
        ipv4_address: 10.0.111.101

  redis-fe:
    image: fetest-redis-fe:8.0.2
    container_name: redis-fe
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - redis-fe-data:/data
    restart: always
    networks:
      fe_net_int:
        ipv4_address: 10.0.111.102

  langflow-fe:
    image: fetest-langflow-fe
    container_name: langflow-fe
    restart: unless-stopped
    depends_on:
      - pgvector-fe
      - postgres-fe
      - redis-fe
    ports:
      - 7860:7860
    env_file:
      - .env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: langflow
    volumes:
      - ../langflow/src/tis_components/:/app/tis_components
      - ../langflow/logs:/app/logs
    networks:
      fe_net_int:
        ipv4_address: 10.0.111.103

networks:
  fe_net_int:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.111.0/24

volumes:
  pgvector-fe-data:
    name: pgvector-fe-data
    driver: local
  postgres-fe-data:
    name: postgres-fe-data
    driver: local
  redis-fe-data:
    name: redis-fe-data
    driver: local
